In [1]:
import pandas as pd
import numpy as np

In [2]:
austin_csv = "Resources/Austin_inspections.csv"
austin_df = pd.read_csv(austin_csv)
austin_df.head()

,Restaurant Name,Common Name,Inspection Date,Score,Address,Facility City,Zip Code,Facility ID,Process Description,Unnamed: 9
0,Circle K Store #2704682,NaN,4/9/2019,84,"6500 S US 183 HWY\nAUSTIN, TX 78744\n(30.16409...",AUSTIN,78744,10762040,Routine Inspection,NaN
1,Harmony School of Excellence-Austin,NaN,4/11/2019,94,"2100 E ST ELMO RD\nAUSTIN, TX 78744\n(30.21007...",AUSTIN,78744,10331481,Routine Inspection,NaN
2,"Honey Baked Ham Company LLC, The",NaN,6/8/2017,96,"9029 RESEARCH BLVD\nAUSTIN, TX 78758\n(30.3732...",AUSTIN,78758,11496272,Routine Inspection,NaN
3,Wingstop,NaN,4/9/2019,80,"1701 W PARMER LN\nAUSTIN, TX 78727\n(30.412316...",AUSTIN,78727,10005294,Routine Inspection,NaN
4,COTA - 34 Chophouse Main Grand Stand,NaN,4/13/2019,96,"9201 CIRCUIT OF THE AMERICAS BLVD\nAUSTIN, TX ...",AUSTIN,78617,11229128,Routine Inspection,NaN

In [3]:
austin_df.columns

Index(['Restaurant Name', 'Common Name', 'Inspection Date', 'Score', 'Address',
       'Facility City', 'Zip Code', 'Facility ID', 'Process Description',
       'Unnamed: 9'],
      dtype='object')

In [5]:
austin_df = austin_df.drop(["Restaurant Name", "Address" ,"Unnamed: 9"], axis = 1)
austin_df

,Common Name,Inspection Date,Score,Facility City,Zip Code,Facility ID,Process Description
0,NaN,4/9/2019,84,AUSTIN,78744,10762040,Routine Inspection
1,NaN,4/11/2019,94,AUSTIN,78744,10331481,Routine Inspection
2,NaN,6/8/2017,96,AUSTIN,78758,11496272,Routine Inspection
3,NaN,4/9/2019,80,AUSTIN,78727,10005294,Routine Inspection
4,NaN,4/13/2019,96,AUSTIN,78617,11229128,Routine Inspection
5,NaN,10/28/2016,79,AUSTIN,78701,2801490,Routine Inspection
6,NaN,4/9/2019,93,AUSTIN,78758,2800716,Routine Inspection
7,NaN,5/4/2018,100,AUSTIN,78745,10929524,Routine Inspection
8,NaN,4/11/2019,100,AUSTIN,78751,10652260,Routine Inspection
9,NaN,4/5/2019,89,AUSTIN,78757,10592894,Routine Inspection
10,NaN,11/2/2017,100,AUSTIN,78750,11509518,Routine Inspection
11,NaN,4/11/2019,86,AUSTIN,78756,11109950,Routine Inspection
12,NaN,4/9/2019,92,AUSTIN,78751,10730249,Routine Inspection
13,NaN,10/13/2017,75,AUSTIN,78701,11639502,Routine Inspection
14,TACO BELL,9/15/2017,97,AUSTIN,78753,11066724,Routine Inspection
15,NaN,4/10/2019,84,AUSTIN,78756,11206262,Routine Inspection
16,NaN,4/9/2019,100,AUSTIN,78748,11637609,Routine Inspection
17,NaN,4/11/2019,94,AUSTIN,78705,2800205,Routine Inspection
18,NaN,10/17/2018,97,AUSTIN,78753,2802959,Routine Inspection
19,NaN,9/10/2018,92,AUSTIN,78746,10643754,Routine Inspection
20,NaN,4/12/2019,86,AUSTIN,78704,11353668,Routine Inspection
21,NaN,4/12/2019,97,AUSTIN,78721,11727007,Routine Inspection
22,NaN,4/14/2017,95,AUSTIN,78613,2801399,Routine Inspection
23,NaN,6/18/2018,85,AUSTIN,78738,10222706,Routine Inspection
24,TACO BELL,2/23/2018,98,AUSTIN,78753,11066724,Routine Inspection
25,NaN,4/5/2019,97,AUSTIN,78751,2802207,Routine Inspection
26,NaN,4/13/2019,100,AUSTIN,78617,11228932,Routine Inspection
27,NaN,2/15/2017,81,AUSTIN,78741,2803758,Routine Inspection
28,NaN,4/19/2018,96,AUSTIN,78702,2800556,Routine Inspection
29,NaN,4/10/2019,75,AUSTIN,78705,2802336,Routine Inspection
...,...,...,...,...,...,...,...
22006,SUBWAY,6/27/2018,93,AUSTIN,78747,10189370,Routine Inspection
22007,NaN,10/31/2016,94,AUSTIN,78734,11289572,Routine Inspection
22008,NaN,8/9/2017,96,AUSTIN,78746,10352305,Routine Inspection
22009,NaN,1/24/2019,97,AUSTIN,78703,2802657,Routine Inspection
22010,NaN,3/3/2017,100,AUSTIN,78748,2803137,Routine Inspection
22011,NaN,8/13/2018,98,AUSTIN,78745,2801047,Routine Inspection
22012,NaN,9/15/2016,92,AUSTIN,78749,10151924,Routine Inspection
22013,NaN,12/20/2018,99,AUSTIN,78702,11712501,Routine Inspection
22014,NaN,6/27/2017,89,AUSTIN,78727,11188727,Routine Inspection
22015,NaN,12/19/2018,98,AUSTIN,78753,11621553,Routine Inspection
22016,NaN,12/21/2016,90,AUSTIN,78753,10125812,Routine Inspection
22017,NaN,4/18/2018,99,AUSTIN,78748,10055908,Routine Inspection
22018,NaN,8/29/2017,84,AUSTIN,78753,10880915,Routine Inspection
22019,NaN,2/16/2018,94,AUSTIN,78747,2802859,Routine Inspection
22020,NaN,3/21/2019,94,AUSTIN,78756,10423805,Routine Inspection
22021,NaN,6/29/2018,100,AUSTIN,78754,11281491,Routine Inspection
22022,NaN,6/23/2017,95,AUSTIN,78723,11459777,Routine Inspection
22023,NaN,7/13/2017,90,AUSTIN,78758,2800930,Routine Inspection
22024,NaN,8/24/2017,94,AUSTIN,78745,10339305,Routine Inspection
22025,NaN,2/7/2019,91,AUSTIN,78749,11833191,Routine Inspection
22026,NaN,4/5/2018,100,AUSTIN,78734,2800942,Routine Inspection
22027,NaN,8/14/2017,95,AUSTIN,78753,2804009,Routine Inspection
22028,NaN,11/21/2018,98,AUSTIN,78730,2803852,Routine Inspection
22029,NaN,4/9/2018,90,AUSTIN,78734,11511869,Routine Inspection
22030,NaN,8/28/2017,71,AUSTIN,78660,11085152,Routine Inspection
22031,NaN,7/26/2017,96,AUSTIN,78753,2801829,Routine Inspection
22032,NaN,12/14/2018,100,AUSTIN,78726,2802625,Routine Inspection
22033,NaN,6/5/2018,95,AUSTIN,78745,11377952,Routine Inspection
22034,NaN,4/26/2017,96,AUSTIN,78723,10322560,Routine Inspection
22035,NaN,5/4/2017,97,AUSTIN,78723,2802195,Routine Inspection

In [6]:
austin_restaurants = austin_df[austin_df["Common Name"].isin(["STARBUCKS", "McDonald's", "Burger King", "SUBWAY", "TACO BELL"])]
austin_restaurants

,Common Name,Inspection Date,Score,Facility City,Zip Code,Facility ID,Process Description
14,TACO BELL,9/15/2017,97,AUSTIN,78753,11066724,Routine Inspection
24,TACO BELL,2/23/2018,98,AUSTIN,78753,11066724,Routine Inspection
64,SUBWAY,4/11/2019,86,AUSTIN,78738,10262005,Routine Inspection
121,TACO BELL,4/10/2019,94,AUSTIN,78753,11066724,Routine Inspection
170,TACO BELL,7/30/2018,100,AUSTIN,78753,11066724,Routine Inspection
175,McDonald's,9/15/2017,97,AUSTIN,78753,2801548,Routine Inspection
178,TACO BELL,2/6/2017,96,AUSTIN,78753,11066724,Routine Inspection
209,McDonald's,7/30/2018,94,AUSTIN,78753,2801548,Routine Inspection
211,STARBUCKS,7/18/2018,98,AUSTIN,78748,10944981,Routine Inspection
215,STARBUCKS,10/20/2016,95,AUSTIN,78613,11034139,Routine Inspection
219,TACO BELL,10/26/2017,96,AUSTIN,78748,11066594,Routine Inspection
253,Burger King,4/17/2019,95,AUSTIN,78741,10840105,Routine Inspection
321,McDonald's,4/10/2019,95,AUSTIN,78753,2801548,Routine Inspection
330,McDonald's,1/6/2017,93,AUSTIN,78753,2801548,Routine Inspection
360,STARBUCKS,3/6/2017,98,AUSTIN,78745,2801590,Routine Inspection
392,McDonald's,2/23/2018,86,AUSTIN,78753,2801548,Routine Inspection
417,McDonald's,1/30/2017,84,AUSTIN,78735,2801429,Routine Inspection
488,STARBUCKS,4/25/2019,96,AUSTIN,78717,2802283,Routine Inspection
506,STARBUCKS,4/26/2019,95,AUSTIN,78726,2802524,Routine Inspection
522,STARBUCKS,4/25/2019,98,AUSTIN,78705,2801411,Routine Inspection
535,SUBWAY,4/25/2019,90,AUSTIN,78749,11298947,Routine Inspection
594,STARBUCKS,10/3/2016,97,AUSTIN,78746,10002742,Routine Inspection
680,McDonald's,4/23/2019,89,AUSTIN,78727,2802299,Routine Inspection
725,TACO BELL,4/28/2017,92,AUSTIN,78745,11066726,Routine Inspection
736,STARBUCKS,9/7/2018,96,AUSTIN,78749,2801731,Routine Inspection
747,STARBUCKS,11/2/2017,96,AUSTIN,78613,11034139,Routine Inspection
851,SUBWAY,12/15/2016,97,AUSTIN,78758,10091620,Routine Inspection
890,SUBWAY,10/6/2017,88,AUSTIN,78735,2802526,Routine Inspection
911,SUBWAY,8/16/2018,92,AUSTIN,78735,2802526,Routine Inspection
924,SUBWAY,11/1/2016,90,AUSTIN,78735,2802526,Routine Inspection
...,...,...,...,...,...,...,...
21348,STARBUCKS,1/10/2019,94,AUSTIN,78738,10262029,Routine Inspection
21352,McDonald's,3/20/2019,97,AUSTIN,78751,2801787,Routine Inspection
21383,McDonald's,8/26/2016,88,AUSTIN,78727,2802305,Routine Inspection
21396,SUBWAY,10/19/2017,91,AUSTIN,78752,11558491,Routine Inspection
21398,TACO BELL,3/18/2019,100,AUSTIN,78753,11066396,Routine Inspection
21418,TACO BELL,8/3/2018,96,AUSTIN,78726,11066752,Routine Inspection
21421,STARBUCKS,7/9/2018,99,AUSTIN,78738,10262029,Routine Inspection
21437,STARBUCKS,3/28/2017,87,AUSTIN,78727,2801629,Routine Inspection
21441,STARBUCKS,3/26/2018,95,AUSTIN,78701,2801814,Routine Inspection
21461,SUBWAY,3/16/2018,94,AUSTIN,78752,11558491,Routine Inspection
21537,SUBWAY,8/9/2017,89,AUSTIN,78731,2801212,Routine Inspection
21558,STARBUCKS,9/19/2017,100,AUSTIN,78734,10999732,Routine Inspection
21582,STARBUCKS,2/23/2017,95,AUSTIN,78701,11075085,Routine Inspection
21596,STARBUCKS,8/10/2016,93,AUSTIN,78701,11075085,Routine Inspection
21602,STARBUCKS,9/21/2016,89,AUSTIN,78701,10086722,Routine Inspection
21633,McDonald's,12/5/2018,94,AUSTIN,78749,2801761,Routine Inspection
21666,STARBUCKS,7/6/2017,96,AUSTIN,78749,10220716,Routine Inspection
21689,SUBWAY,8/27/2018,99,AUSTIN,78758,11299024,Routine Inspection
21754,TACO BELL,3/19/2018,94,AUSTIN,78734,11066788,Routine Inspection
21785,SUBWAY,3/8/2018,86,AUSTIN,78701,10716361,Routine Inspection
21794,STARBUCKS,7/20/2018,100,AUSTIN,78726,2801732,Routine Inspection
21801,McDonald's,1/25/2018,94,AUSTIN,78758,2802280,Routine Inspection
21832,SUBWAY,5/22/2017,96,AUSTIN,78758,10385802,Routine Inspection
21843,TACO BELL,8/21/2018,96,AUSTIN,78757,11066790,Routine Inspection
21888,TACO BELL,2/27/2018,98,AUSTIN,78717,11066586,Routine Inspection
21902,SUBWAY,8/11/2017,96,AUSTIN,78721,2802134,Routine Inspection
21926,SUBWAY,9/21/2017,94,AUSTIN,78749,11298947,Routine Inspection
21951,STARBUCKS,8/9/2016,100,AUSTIN,78734,10999732,Routine Inspection
21969,McDonald's,10/1/2018,82,AUSTIN,78750,2802294,Routine Inspection
22006,SUBWAY,6/27/2018,93,AUSTIN,78747,10189370,Routine Inspection

In [7]:
la_csv = "Resources/LA_inspections.csv"
la_df = pd.read_csv(la_csv)
la_df.head()

,serial_number,activity_date,facility_name,Common Name,score,grade,service_code,service_description,employee_id,facility_address,...,facility_id,facility_state,facility_zip,owner_id,owner_name,pe_description,program_element_pe,program_name,program_status,record_id
0,DAJ00E07B,12/29/2017 0:00,HABITAT COFFEE SHOP,NaN,95,A,1,ROUTINE INSPECTION,EE0000923,3708 N EAGLE ROCK BLVD,...,FA0170465,CA,90065,OW0178123,GLASSELL COFFEE SHOP LLC,RESTAURANT (0-30) SEATS MODERATE RISK,1631,HABITAT COFFEE SHOP,ACTIVE,PR0160774
1,DAQOKRFZB,12/29/2017 0:00,REILLY'S,NaN,92,A,1,ROUTINE INSPECTION,EE0000633,100 WORLD WAY # 120,...,FA0244690,CA,90045,OW0208441,"AREAS SKYVIEW LAX JV, LLC",RESTAURANT (0-30) SEATS MODERATE RISK,1631,REILLY'S,ACTIVE,PR0193026
2,DASJI4LUR,12/29/2017 0:00,STREET CHURROS,NaN,93,A,1,ROUTINE INSPECTION,EE0000835,6801 HOLLYWOOD BLVD # 253,...,FA0224109,CA,90028,OW0228670,"STREETCHURROS, INC",RESTAURANT (0-30) SEATS LOW RISK,1630,STREET CHURROS,ACTIVE,PR0179282
3,DA40LU5AT,12/29/2017 0:00,TRINITI ECHO PARK,NaN,94,A,1,ROUTINE INSPECTION,EE0000923,1814 W SUNSET BLVD,...,FA0252528,CA,90026-3227,OW0246287,AMERICAN HOSPITALITY,RESTAURANT (0-30) SEATS MODERATE RISK,1631,TRINITI ECHO PARK,ACTIVE,PR0201836
4,DAXV2RMYC,12/29/2017 0:00,POLLEN,NaN,94,A,1,ROUTINE INSPECTION,EE0000923,2100 ECHO PARK AVE,...,FA0252789,CA,90026,OW0246479,"POLLEN AND PASTRY , LLC",RESTAURANT (0-30) SEATS MODERATE RISK,1631,POLLEN,ACTIVE,PR0202148

In [8]:
la_df.columns

Index(['serial_number', 'activity_date', 'facility_name', 'Common Name',
       'score', 'grade', 'service_code', 'service_description', 'employee_id',
       'facility_address', 'facility_city', 'facility_id', 'facility_state',
       'facility_zip', 'owner_id', 'owner_name', 'pe_description',
       'program_element_pe', 'program_name', 'program_status', 'record_id'],
      dtype='object')

In [9]:
la_df = la_df.drop(["facility_name", "service_description","service_code", "employee_id", "facility_address", "facility_state", "owner_id", "owner_name", "pe_description", "program_element_pe", "program_name", "program_status", "record_id"], axis = 1)
la_df

,serial_number,activity_date,Common Name,score,grade,facility_city,facility_id,facility_zip
0,DAJ00E07B,12/29/2017 0:00,NaN,95,A,LOS ANGELES,FA0170465,90065
1,DAQOKRFZB,12/29/2017 0:00,NaN,92,A,LOS ANGELES,FA0244690,90045
2,DASJI4LUR,12/29/2017 0:00,NaN,93,A,LOS ANGELES,FA0224109,90028
3,DA40LU5AT,12/29/2017 0:00,NaN,94,A,LOS ANGELES,FA0252528,90026-3227
4,DAXV2RMYC,12/29/2017 0:00,NaN,94,A,LOS ANGELES,FA0252789,90026
5,DAMV56BMJ,12/29/2017 0:00,NaN,93,A,LOS ANGELES,FA0245224,90034
6,DAKSJB0AB,12/29/2017 0:00,NaN,95,A,LOS ANGELES,FA0243779,90043-4706
7,DAQOJLNCD,12/29/2017 0:00,NaN,91,A,LOS ANGELES,FA0225926,90045
8,DAACRFWTS,12/29/2017 0:00,NaN,95,A,LOS ANGELES,FA0248964,90020
9,DAE1JXAWW,12/29/2017 0:00,NaN,91,A,LOS ANGELES,FA0002761,90065
10,DAHKJFBMR,12/28/2017 0:00,NaN,95,A,LOS ANGELES,FA0137987,91604
11,DASL61OZ3,12/28/2017 0:00,NaN,97,A,LOS ANGELES,FA0021238,90027
12,DAYOUBUYG,12/28/2017 0:00,NaN,95,A,LOS ANGELES,FA0044972,90006
13,DA3N76M8U,12/28/2017 0:00,NaN,90,A,LOS ANGELES,FA0163115,90020
14,DAK90PBPD,12/28/2017 0:00,NaN,90,A,LOS ANGELES,FA0044449,90043
15,DAA1OISIX,12/28/2017 0:00,NaN,92,A,LOS ANGELES,FA0138657,90026
16,DAFXWIUCE,12/28/2017 0:00,NaN,98,A,LOS ANGELES,FA0062180,90006
17,DAH1WNPMC,12/28/2017 0:00,NaN,97,A,LOS ANGELES,FA0027722,90010
18,DAKBEMZRR,12/28/2017 0:00,NaN,85,B,LOS ANGELES,FA0047448,90064
19,DACQXFMEG,12/28/2017 0:00,NaN,97,A,LOS ANGELES,FA0225480,90004
20,DATY0A05H,12/28/2017 0:00,NaN,92,A,LOS ANGELES,FA0138424,90046
21,DAF0GFYS4,12/28/2017 0:00,NaN,93,A,LOS ANGELES,FA0248072,90045
22,DAWIMW6RR,12/28/2017 0:00,NaN,91,A,LOS ANGELES,FA0010340,90005
23,DAS9HSZUC,12/28/2017 0:00,NaN,92,A,LOS ANGELES,FA0043262,90010
24,DAASUGWDB,12/28/2017 0:00,NaN,93,A,LOS ANGELES,FA0164018,90010
25,DAIKIC6SX,12/28/2017 0:00,NaN,82,B,LOS ANGELES,FA0242973,90015-2392
26,DAKGAPBU1,12/28/2017 0:00,NaN,91,A,LOS ANGELES,FA0036598,90046
27,DAVC3OO1J,12/28/2017 0:00,NaN,90,A,LOS ANGELES,FA0230665,90048
28,DAO9O7VBX,12/28/2017 0:00,NaN,97,A,LOS ANGELES,FA0065185,90023
29,DA9YVUZ60,12/28/2017 0:00,NaN,90,A,LOS ANGELES,FA0166559,90048
...,...,...,...,...,...,...,...,...
67543,DAZVTR1NF,4/2/2018 0:00,NaN,90,A,LOS ANGELES,FA0032501,90017
67544,DAZVX79JI,6/29/2018 0:00,NaN,97,A,LOS ANGELES,FA0025625,90017
67545,DAZWBE2DG,6/26/2018 0:00,NaN,97,A,LOS ANGELES,FA0045686,90043
67546,DAZWBXLRM,5/3/2018 0:00,NaN,98,A,LOS ANGELES,FA0014927,90027
67547,DAZWH4SJM,7/11/2018 0:00,NaN,91,A,LOS ANGELES,FA0249180,90020
67548,DAZWJEDRJ,4/24/2018 0:00,NaN,94,A,LOS ANGELES,FA0258583,90013-2345
67549,DAZWMHIUW,5/17/2018 0:00,NaN,92,A,LOS ANGELES,FA0239698,90015
67550,DAZWPOZW7,4/18/2018 0:00,NaN,90,A,LOS ANGELES,FA0007732,90001
67551,DAZWUXUTL,5/9/2018 0:00,NaN,97,A,LOS ANGELES,FA0259337,90015-3135
67552,DAZWZPJE5,7/18/2018 0:00,NaN,90,A,LOS ANGELES,FA0250610,90020
67553,DAZX00OCL,6/4/2018 0:00,NaN,92,A,LOS ANGELES,FA0041012,90012
67554,DAZX7YSGD,7/17/2018 0:00,NaN,93,A,LOS ANGELES,FA0252385,90020-4191
67555,DAZX997IR,4/27/2018 0:00,NaN,90,A,LOS ANGELES,FA0158757,90048
67556,DAZXCQ0PW,5/7/2018 0:00,NaN,95,A,LOS ANGELES,FA0163699,90012
67557,DAZXDKPMM,5/29/2018 0:00,McDonald's,94,A,LOS ANGELES,FA0038664,90042
67558,DAZXFBW1P,7/10/2018 0:00,NaN,91,A,LOS ANGELES,FA0051217,90028
67559,DAZXL3ZTT,4/17/2018 0:00,McDonald's,96,A,LOS ANGELES,FA0066639,90028
67560,DAZXZIAKJ,6/27/2018 0:00,NaN,96,A,LOS ANGELES,FA0258279,90066
67561,DAZY2BFVC,4/11/2018 0:00,NaN,91,A,LOS ANGELES,FA0249798,90023-2525
67562,DAZYBSG0L,6/8/2018 0:00,NaN,95,A,LOS ANGELES,FA0175701,90012
67563,DAZYCVZVV,6/29/2018 0:00,NaN,99,A,LOS ANGELES,FA0252128,90019
67564,DAZYFFUVT,6/12/2018 0:00,NaN,96,A,LOS ANGELES,FA0243033,90029
67565,DAZYNPS0R,6/21/2018 0:00,NaN,97,A,LOS ANGELES,FA0048134,90028
67566,DAZYUYH2B,5/1/2018 0:00,NaN,90,A,LOS ANGELES,FA0164532,90291
67567,DAZYVBSLP,7/10/2018 0:00,NaN,92,A,LOS ANGELES,FA0166078,90004
67568,DAZZ4BFUD,6/15/2018 0:00,NaN,94,A,LOS ANGELES,FA0159703,90012
67569,DAZZ4TRBY,5/16/2018 0:00,NaN,96,A,LOS ANGELES,FA0137540,90018
67570,DAZZ9YUS4,4/20/2018 0:00,NaN,91,A,LOS ANGELES,FA0170167,90011
67571,DAZZJBQUO,4/17/2018 0:00,NaN,95,A,LOS ANGELES,FA0225467,90025
67572,DAZZL6GP3,6/7/2018 0:00,NaN,97,A,LOS ANGELES,FA0049848,90063

In [10]:
la_restaurants = la_df[la_df["Common Name"].isin(["STARBUCKS", "McDonald's", "Burger King", "SUBWAY", "TACO BELL"])]
la_restaurants

,serial_number,activity_date,Common Name,score,grade,facility_city,facility_id,facility_zip
42,DAQKIE2OT,12/27/2017 0:00,SUBWAY,95,A,LOS ANGELES,FA0034746,90012
74,DARQKZYXV,12/27/2017 0:00,McDonald's,96,A,LOS ANGELES,FA0038653,90065
86,DAEOVTKME,12/27/2017 0:00,SUBWAY,91,A,LOS ANGELES,FA0049818,90012
110,DAE886X1B,12/26/2017 0:00,McDonald's,97,A,LOS ANGELES,FA0038675,90033
127,DAK9BVPJO,12/26/2017 0:00,SUBWAY,94,A,LOS ANGELES,FA0071195,90014
180,DAKIJM35U,12/21/2017 0:00,SUBWAY,97,A,LOS ANGELES,FA0071216,90045
203,DAPEXG4Q0,12/20/2017 0:00,TACO BELL,91,A,LOS ANGELES,FA0036007,90044
208,DAMBAONE6,12/20/2017 0:00,SUBWAY,93,A,LOS ANGELES,FA0071199,90010
293,DA0L1QOII,12/19/2017 0:00,SUBWAY,95,A,LOS ANGELES,FA0164944,90026
347,DAT0A0ED5,12/18/2017 0:00,SUBWAY,98,A,LOS ANGELES,FA0049820,90015
369,DA5IOIGDB,12/18/2017 0:00,Burger King,99,A,LOS ANGELES,FA0137635,90061
377,DABQN6IMC,12/15/2017 0:00,SUBWAY,95,A,LOS ANGELES,FA0251903,90045-5312
420,DAAOSORFW,12/14/2017 0:00,McDonald's,98,A,LOS ANGELES,FA0024166,90021
449,DAVYC7AFF,12/13/2017 0:00,McDonald's,97,A,LOS ANGELES,FA0039676,90015
460,DA4BSDPGU,12/13/2017 0:00,SUBWAY,91,A,LOS ANGELES,FA0049299,90046
474,DAE0XDWY0,12/13/2017 0:00,SUBWAY,95,A,LOS ANGELES,FA0049827,90045
481,DAQQ39HAQ,12/13/2017 0:00,SUBWAY,97,A,LOS ANGELES,FA0071269,90015
500,DADZANJUI,12/11/2017 0:00,SUBWAY,90,A,LOS ANGELES,FA0071172,90016
511,DA8NWUW0H,12/13/2017 0:00,McDonald's,95,A,LOS ANGELES,FA0066636,90006
560,DA9PLE8O0,12/12/2017 0:00,McDonald's,92,A,LOS ANGELES,FA0039644,90044-5527
581,DALDPN2PV,12/11/2017 0:00,STARBUCKS,97,A,LOS ANGELES,FA0049363,90017
655,DAAQ23HN3,12/9/2017 0:00,SUBWAY,98,A,LOS ANGELES,FA0034927,90002
659,DAYUHAM0K,12/8/2017 0:00,McDonald's,90,A,LOS ANGELES,FA0066713,90045
660,DACRSDZS8,12/8/2017 0:00,SUBWAY,94,A,LOS ANGELES,FA0239653,90024
661,DASLGOORM,12/8/2017 0:00,SUBWAY,98,A,LOS ANGELES,FA0049259,90015
673,DAVR9WLXP,12/8/2017 0:00,TACO BELL,96,A,LOS ANGELES,FA0050180,90045
682,DA3020UPF,12/8/2017 0:00,SUBWAY,97,A,LOS ANGELES,FA0049128,90062
706,DACFCNCV4,12/7/2017 0:00,McDonald's,94,A,LOS ANGELES,FA0038298,90044
723,DAXDVFEFT,12/7/2017 0:00,SUBWAY,85,B,LOS ANGELES,FA0071216,90045
753,DAJBY20HV,12/6/2017 0:00,SUBWAY,96,A,LOS ANGELES,FA0071232,90003
...,...,...,...,...,...,...,...,...
66447,DAVXSBV0P,5/16/2018 0:00,McDonald's,98,A,LOS ANGELES,FA0177629,90041
66471,DAW0RLZLI,4/16/2018 0:00,SUBWAY,99,A,LOS ANGELES,FA0175760,90022
66489,DAW57NIPK,7/24/2018 0:00,Burger King,98,A,LOS ANGELES,FA0058805,90028
66533,DAWCOUMNH,6/5/2018 0:00,SUBWAY,90,A,LOS ANGELES,FA0049966,90045
66542,DAWDKVLGU,6/27/2018 0:00,SUBWAY,96,A,LOS ANGELES,FA0049908,90021
66564,DAWGRTA7Z,5/30/2018 0:00,SUBWAY,94,A,LOS ANGELES,FA0034720,90033
66628,DAWNGDIMR,4/23/2018 0:00,SUBWAY,90,A,LOS ANGELES,FA0034882,90071
66654,DAWPMWYGO,5/1/2018 0:00,SUBWAY,94,A,LOS ANGELES,FA0049818,90012
66861,DAXHKNTE7,5/16/2018 0:00,Burger King,95,A,LOS ANGELES,FA0011330,90019
66948,DAXQKV5XR,6/13/2018 0:00,SUBWAY,100,A,LOS ANGELES,FA0034867,90016
66949,DAXQOKSES,5/9/2018 0:00,McDonald's,98,A,LOS ANGELES,FA0039644,90044-5527
67010,DAXYO0YHQ,5/23/2018 0:00,STARBUCKS,97,A,LOS ANGELES,FA0160767,90042
67017,DAXZNZCF0,6/18/2018 0:00,SUBWAY,94,A,LOS ANGELES,FA0071196,90019
67022,DAY09P20O,7/11/2018 0:00,Burger King,97,A,LOS ANGELES,FA0011345,90001
67037,DAY22V2LC,7/24/2018 0:00,McDonald's,98,A,LOS ANGELES,FA0038312,90022
67089,DAYBAERTM,4/20/2018 0:00,Burger King,98,A,LOS ANGELES,FA0170611,90006
67135,DAYG24A67,5/3/2018 0:00,SUBWAY,98,A,LOS ANGELES,FA0071216,90045
67172,DAYJVSTIG,7/9/2018 0:00,TACO BELL,91,A,LOS ANGELES,FA0248290,90016-3604
67173,DAYK81CZ3,7/10/2018 0:00,STARBUCKS,87,B,LOS ANGELES,FA0070912,90045
67197,DAYN8P8AX,4/25/2018 0:00,McDonald's,95,A,LOS ANGELES,FA0256619,90006-5806
67288,DAYXFDR0O,6/19/2018 0:00,SUBWAY,97,A,LOS ANGELES,FA0170519,90002
67315,DAZ0FG2AJ,4/12/2018 0:00,STARBUCKS,98,A,LOS ANGELES,FA0048827,90028
67393,DAZE1MGOV,5/2/2018 0:00,McDonald's,97,A,LOS ANGELES,FA0039676,90015
67413,DAZFYHTXS,6/11/2018 0:00,McDonald's,98,A,LOS ANGELES,FA0244055,90037
67417,DAZGGEBOX,5/4/2018 0:00,SUBWAY,97,A,LOS ANGELES,FA0256455,90033-2415
67495,DAZPMXSCY,6/13/2018 0:00,STARBUCKS,92,A,LOS ANGELES,FA0048678,90048
67501,DAZQEV5SB,6/25/2018 0:00,SUBWAY,97,A,LOS ANGELES,FA0225832,90036
67523,DAZTBEW5K,6/6/2018 0:00,TACO BELL,95,A,LOS ANGELES,FA0033131,90011
67557,DAZXDKPMM,5/29/2018 0:00,McDonald's,94,A,LOS ANGELES,FA0038664,90042
67559,DAZXL3ZTT,4/17/2018 0:00,McDonald's,96,A,LOS ANGELES,FA0066639,90028

In [11]:
austin_restaurants['Common Name'].value_counts()

STARBUCKS      242
SUBWAY         226
McDonald's     163
TACO BELL      126
Burger King     55
Name: Common Name, dtype: int64

In [12]:
la_restaurants['Common Name'].value_counts()

SUBWAY         799
McDonald's     434
STARBUCKS      364
Burger King    215
TACO BELL      174
Name: Common Name, dtype: int64